#This is là File Yaml config nha :) mới biết lun á
api_key: api_key
email_credential:
  email: minh1122000@gmail.com
  password: abc@1234
port: 8080
postgres_config:
  host: localhost
  port: 5432
  user: postgres
  password: 123456
jwt-secret: "averyverystrongsecret"
